### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nakajima97** [nakajima97/next-simple-ai-chat#33]
# Scope
`yarn dev`実行した際に出る以下のエラーを解決する
```
Error: No router instance found. you should only use "next/router" inside the client side of your app. https://nextjs.org/docs/messages/no-router-instance
    at eK (/home/user/source/next-simple-ai-chat/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:21244)
    at e1.push (/home/user/source/next-simple-ai-chat/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:21952)
    at eval (webpack-internal:///./src/hooks/useProtectedRoute.ts:28:24)
    at file:///home/user/source/next-simple-ai-chat/node_modules/@firebase/auth/dist/node-esm/totp-0b2bfc5c.js:2989:13
 ⨯ unhandledRejection: Error: No router instance found. you should only use "next/router" inside the client side of your app. https://nextjs.org/docs/messages/no-router-instance
    at eK (/home/user/source/next-simple-ai-chat/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:21244)
    at e1.push (/home/user/source/next-simple-ai-chat/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:21952)
    at eval (webpack-internal:///./src/hooks/useProtectedRoute.ts:28:24)
    at file:///home/user/source/next-simple-ai-chat/node_modules/@firebase/auth/dist/node-esm/totp-0b2bfc5c.js:2989:13
 ⨯ unhandledRejection: Error: No router instance found. you should only use "next/router" inside the client side of your app. https://nextjs.org/docs/messages/no-router-instance
    at eK (/home/user/source/next-simple-ai-chat/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:21244)
    at e1.push (/home/user/source/next-simple-ai-chat/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:21952)
    at eval (webpack-internal:///./src/hooks/useProtectedRoute.ts:28:24)
    at file:///home/user/source/next-simple-ai-chat/node_modules/@firebase/auth/dist/node-esm/totp-0b2bfc5c.js:2989:13
 GET /chat 200 in 54ms
 ⨯ unhandledRejection: Error: No router instance found. you should only use "next/router" inside the client side of your app. https://nextjs.org/docs/messages/no-router-instance
    at eK (/home/user/source/next-simple-ai-chat/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:21244)
    at e1.push (/home/user/source/next-simple-ai-chat/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:21952)
    at eval (webpack-internal:///./src/hooks/useProtectedRoute.ts:28:24)
    at file:///home/user/source/next-simple-ai-chat/node_modules/@firebase/auth/dist/node-esm/totp-0b2bfc5c.js:2989:13
 ⨯ unhandledRejection: Error: No router instance found. you should only use "next/router" inside the client side of your app. https://nextjs.org/docs/messages/no-router-instance
    at eK (/home/user/source/next-simple-ai-chat/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:21244)
    at e1.push (/home/user/source/next-simple-ai-chat/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:21952)
    at eval (webpack-internal:///./src/hooks/useProtectedRoute.ts:28:24)
    at file:///home/user/source/next-simple-ai-chat/node_modules/@firebase/auth/dist/node-esm/totp-0b2bfc5c.js:2989:13
```

# Background
実装を行う背景を記載する

# Problem Statement
解決したい課題を記載する

# Proposal
解決する方法を記載する

**Comment by nakajima97** [comment]
issueに記載したエラーは確認できず
